#!/bin/bash
# WATERS 3-Node P2P Test Scenario
# Usage: Run on each node, then orchestrate from node1

NODE1_PORT=42069
NODE2_PORT=42070
NODE3_PORT=42071

echo "╔══════════════════════════════════════════════╗"
echo "║   WATERS v0.4 — 3-Node P2P Test Scenario  ║"
echo "╚══════════════════════════════════════════════╝"
echo ""
echo "Старт ноды 1 (172:42069) — сервер:"
echo "  export REDIS_URL=redis://127.0.0.1:6379"
echo "  DEEPSEEK_API_KEY=sk-xxx ./waters-node --port $NODE1_PORT"
echo ""
echo "Старт ноды 2 (дача:42070):"
echo "  DEEPSEEK_API_KEY=sk-xxx ./waters-node --port $NODE2_PORT"
echo ""
echo "Старт ноды 3 (дом:42071):"
echo "  DEEPSEEK_API_KEY=sk-xxx ./waters-node --port $NODE3_PORT"
echo ""
echo "═══ СЦЕНАРИЙ ТЕСТА ═══"
echo ""
echo "1. Соединить ноды:"
echo "   /connect <ip_дачи>:42070"
echo "   /connect <ip_дома>:42071"
echo ""
echo "2. Проверить связь:"
echo "   status"
echo "   Должно быть: Peers: 2"
echo ""
echo "3. Создать агента-разведчика:"
echo "   /agent create waters-scout"
echo "   /assign agent.1 собери данные о погоде на Марсе"
echo ""
echo "4. Чат между нодами:"
echo "   /say 1 привет, я сервер 177"
echo "   (нода 2 видит в чате)" 
echo ""
echo "5. Мнения агентов:"
echo "   агенты говорят в чат (/opinions)"
echo ""
echo "6. Импорт агента:"
echo "   /import /tmp/agent.md"
echo ""
echo "7. Проверить рейтинг:"
echo "   /top"
echo "   /rating waters-scout"
echo ""
echo "═══ ВСЁ ✅ ═══"
